account/urls.py
from django.urls import path, include
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm, CustomPasswordResetForm, CustomSetPasswordForm
from .api.urls import urlpatters as api_urls

app_name = 'account'

urlpatterns = [
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('login/', auth_views.LoginView.as_view(
         authentication_form=LoginForm,
         template_name='account/user_login.html',
         redirect_authenticated_user='/'
         ), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
         template_name='account/password_reset.html',
         email_template_name='account/password_reset_email.html',
         form_class=CustomPasswordResetForm,
         success_url=reverse_lazy('account:password_reset_done')
         ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
         template_name='account/password_reset_done.html',
         ), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
         template_name='account/password_reset_confirm.html',
         form_class=CustomSetPasswordForm,
         success_url=reverse_lazy('account:password_reset_complete')
         ), name='password_reset_confirm'),

    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
         template_name='account/password_reset_complete.html',
         ), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:id>', views.profile, name='profile_for_staff'),
    path('profile/change/<int:id>/', views.UpdateProfile.as_view(), name='change_profile'),
    path('profile/change_image/', views.change_image, name='change_image'),
    path('profile/remove_image/', views.remove_image, name='remove_image'),
    path('profile/change_password/', views.PasswordChange.as_view(), name='change_password'),
    path('profile/change_email/<int:id>', views.EmailChange.as_view(), name='change_email'),
    path('users/<category>/', views.UserList.as_view(), name='users'),
    path('blacklist/<int:user_id>/<category>/', views.blacklist, name='blacklist'),
    path('permissions/<int:user_id>/<category>/', views.permissions, name='permissions'),
    path('api/', include(api_urls))
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')]

e_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('', include('catalog.urls')),
    path('api-auth/', include('rest_framework.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    {%load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/navbar/navbar.css' %}">
    <title>HSBC</title>
    {%block style%}

    {%endblock%}
</head>
<body>

    {%block content%}

    {%endblock%}

<script src="//static.liqpay.ua/libjs/checkout.js" async></script>
<script src="//static.liqpay.ua/libjs/checkout.js" async></script>


    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

   <script src="{% static 'js/bootstrap.min.js' %}"></script>
   <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
           integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<!-- jQuery -->
   <script src="/examples/vendors/jquery/jquery-3.2.1.min.js"></script>
<!-- Popper -->
   <script src="/examples/vendors/popper.js/popper.min.js"></script>
<!-- Bootstrap JS -->
   <script src="/examples/vendors/bootstrap-4/js/bootstrap.min.js"></script>

</body>
</html>

templates/navbar.html
{%load static %}
<link rel="stylesheet" href="{% static 'css/navbar/navbar.css'%}">
<link rel="stylesheet" href="{% static 'css/navbar/navbar-media.css'%}">
<nav class="navbar navbar-expand-md navbar-dark mb-4" style="background: #212529;">
            <a class="navbar-brand" href="#">
               <img alt="Brand" class="img-responsive" style="background: white" width=160rem height=auto src="static/navbar_image/hsbc-logo-black-and-white.png">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <h4 style="color:white">Navigation</h4>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      {% if user.is_authenticated %}
                          <a class="dropdown-item" href="{% url 'account:profile'%}">Profile</a>
                      {% endif %}
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'catalog:product_list' %}">Main page</a>
                    </div>
                </li>


              </ul>


                <div class="container" id="store">
                        <form class="form-inline my-2 my-lg-0" action="">
                            <input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search" name="search">
                            <button class="btn btn-warning my-2 my-sm-0" id="sub" type="submit">Искать</button>
                        </form>
                </div>

                     {%if user.is_authenticated%}
                         <a href="{% url 'account:profile'%}"><img alt="Main user image" id="main_img" src="{{user.main_image.url}}"></a>
                     {%else%}
                     <div class="btn-group" role="group" aria-label="Basic example">
                          <a class="btn btn-warning" href="{% url 'account:registration'%}">Registration</a>
                          <a class="btn btn-warning" style="white-space: nowrap" href="{% url 'account:login'%}">Log in</a>
                    </div>
                     {%endif%}
                </div>

        </nav>

templates/navbar_profile.html
<nav class="navbar navbar-expand-lg navbar-light bg-white" style="background: #212529;" >
    <a class="navbar-brand" href="#">
        <img alt="Brand" class="img-responsive" style="background: white" width=160rem height=auto src="media/navbar_image/hsbc-logo-black-and-white.png">
    </a>
    <ul class="navbar-nav mr-auto" style="margin-left:700px">
      <li class="nav-item active">
        <a class="nav-link" href="">Main page<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Friends</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Massages</a>
      </li>
    </ul>

    <div>
        <a class="btn btn-dark" style="white-space: nowrap" href="{% url 'account:change_profile' user.id%}">Change profile</a>
        <a class="btn btn-dark" style="white-space: nowrap" href="{% url 'account:logout' %}">Log out</a>
    </div>
</nav>