cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')]

catalog/api/urls.py
from django.urls import path, include
from . import views as api_view

from rest_framework.routers import DefaultRouter

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register('products', api_view.ProductViewSet),
router.register('category', api_view.CategoryViewSet),
router.register('comment', api_view.CommentViewSet),
router.register('like', api_view.LikeViewSet)

# The API URLs are now determined automatically by the router.
urlpatterns = [
    path('', include(router.urls))
]

catalog/urls.py
from django.urls import path, include
from . import views
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from .forms import CategoryCreationForm
from .models import Category
from .api.urls import urlpatterns as api

app_name = 'catalog'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('<int:category_id>', views.ProductList.as_view(), name='select_category'),
    path('product_create', views.ProductCreateView.as_view(), name='product_create'),
    path('product_update/<int:product_id>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('product_detail/<int:product_id>', views.product_detail, name='product_detail'),
    path('category_create/', CreateView.as_view(
         form_class=CategoryCreationForm,
         model=Category,
         success_url=reverse_lazy('catalog:product_list'),
         template_name='catalog/category_create.html'
         ), name='category_create'
         ),
    path('category_update/<int:id>', UpdateView.as_view(
         context_object_name='up_category',
         form_class=CategoryCreationForm,
         model=Category,
         pk_url_kwarg='id',
         success_url=reverse_lazy('catalog:product_list'),
         template_name='catalog/category_create.html'
         ), name='category_update'),
    path('category_delete/<int:id>', views.category_delete, name='category_delete'),
    path('category_admin/', ListView.as_view(
         context_object_name='categories',
         model=Category,
         queryset=Category.objects.all(),
         template_name='catalog/category_admin.html'
         ), name='category_admin'),
    path('comment_create/<int:product_id>/', views.comment_create, name='comment_create'),
    path('comment_edit/<int:comment_id>/<int:product_id>/', views.comment_edit, name='comment_edit'),
    path('comment_delete/<int:comment_id>/<int:product_id>/', views.comment_delete, name='comment_delete'),
    path('like/<int:comment_id>/<int:product_id>/', views.like, name='like'),
    path('unlike/<int:like_id>/<int:product_id>/', views.unlike, name='unlike'),
    path('api/', include(api))
]

e_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('', include('catalog.urls')),
    path('api-auth/', include('rest_framework.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from account.models import CustomUser
from .model_mixins import CacheDeleteMixin


class Category(CacheDeleteMixin, models.Model):
    title = models.CharField(max_length=150, unique=True)

    def get_absolute_url(self):
        return reverse('catalog:select_category', args=[self.id])

    def __str__(self):
        return self.title


class Product(CacheDeleteMixin, models.Model):
    title = models.CharField(max_length=20)
    image = models.ImageField(
        upload_to='product_image/product_photo/main_photo/',
        default='product_image/default_image/default-no-image.png'
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', null=True)
    description = models.TextField(max_length=1000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse('catalog:product_detail', args=[self.id])

    def __str__(self):
        return self.title


class Gallery(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_image/product_photo/')

    def __str__(self):
        return '{}'.format(self.image)


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField(max_length=1000)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(null=True)

    def __str__(self):
        return '{}...'.format(self.text[:5])


class Like(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='likes')

    def __str__(self):
        return 'Like {}'.format(self.id)

catalog/forms.py
from django import forms
from .models import Product, Gallery, Category
from .widgets import ImageWidget
from django.forms.widgets import TextInput


class GalleryForm(forms.ModelForm):
    image = forms.ImageField(widget=ImageWidget(), required=False, label='')

    class Meta:
        model = Gallery
        fields = ('image',)


class ProductCreationForm(forms.ModelForm):
    image = forms.ImageField(widget=ImageWidget(), required=False)

    class Meta:
        model = Product
        fields = ('title', 'description', 'price', 'quantity', 'category', 'image')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {'class': 'form-control'}


class CategoryCreationForm(forms.ModelForm):
    title = forms.CharField(
        widget=TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Category
        fields = ('title',)

catalog/api/views.py
from .permission import IsOwnerOrReadOnly, AdminOrReadonlyPermission
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from .serializers import ProductSerializer, CategorySerializer, LikeSerializer, CommentSerializer
from catalog.models import Product, Category, Comment, Like
from rest_framework import viewsets


class ProductViewSet(viewsets.ModelViewSet):

    serializer_class = ProductSerializer
    queryset = Product.objects.filter().order_by('id')
    permission_classes = [AdminOrReadonlyPermission]


class CategoryViewSet(viewsets.ModelViewSet):
    permission_classes = [AdminOrReadonlyPermission]
    serializer_class = CategorySerializer
    queryset = Category.objects.filter().order_by('id')


class CommentViewSet(viewsets.ModelViewSet):
    serializer_class = CommentSerializer
    queryset = Comment.objects.filter().order_by('id')
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class LikeViewSet(viewsets.ModelViewSet):
    serializer_class = LikeSerializer
    queryset = Like.objects.filter().order_by('id')
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

catalog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from .mixins import ProductCreateUpdateMixin
from .models import Product, Category, Comment, Like
from django.utils import timezone
from cart.views import CartAddProductForm
from django.contrib.admin.views.decorators import staff_member_required
from django.core.cache import cache


class ProductList(ListView):
    model = Product
    page_kwarg = 12
    template_name = 'catalog/product_list.html'

    def get_context_data(self):
        category_id = self.kwargs.get('category_id')
        current_category = self.get_category(category_id)

        context = {
            'products': self.get_products(category_id, current_category),
            'categories': self.get_categories(),
            'current_category': self.get_category(category_id),
        }

        return context

    @staticmethod
    def get_products_all():
        products = cache.get('products')
        if products is None:
            products = Product.objects.all()
            cache.set('products', products)
        return products

    @staticmethod
    def get_categories():
        categories = cache.get('categories')
        if categories is None:
            categories = Category.objects.all()
            cache.set('categories', categories)
        return categories

    @staticmethod
    def get_category(category_id):
        if category_id is not None:
            category_cache_key = 'category_{}'.format(category_id)
            category = cache.get(category_cache_key)
            if category is None:
                category = get_object_or_404(Category, id=category_id)
                cache.set(category_cache_key, category)
            return category

    def get_products(self, category_id, category):
        if category_id is not None:
            product_category_cache = "products_of_category_{}".format(category_id)
            products_of_category = cache.get(product_category_cache)
            if products_of_category is None:
                products_of_category = category.products.all()
                cache.set(product_category_cache, products_of_category)
            return products_of_category

        return self.get_products_all()


def product_detail(request, product_id):
    product_cache = 'product_{}'.format(product_id)
    product = cache.get(product_cache)
    if product is None:
        product = get_object_or_404(Product, id=product_id)
        cache.set(product_cache, product)

    context = {
        'product': product,
        'comments': product.comments.all(),
        'cart_product_form':  CartAddProductForm(choices=product.quantity + 1),
        }

    return render(request, 'catalog/product_detail.html', context)


class ProductCreateView(ProductCreateUpdateMixin):
    pass


class ProductUpdateView(ProductCreateUpdateMixin):

    def get_form_kwargs(self):
        product_id = self.kwargs['product_id']
        product_cache = 'product_{}'.format(product_id)
        product = cache.get(product_cache)
        if product is None:
            product = get_object_or_404(Product, id=product_id)
        self.kwargs['product'] = product

        return self.kwargs

    def get(self, *args, **kwargs):
        kwargs = self.get_form_kwargs()
        return super().get(*args, *kwargs)

    def post(self, *args, **kwargs):
        kwargs = self.get_form_kwargs()
        return super().post(*args, *kwargs)


@staff_member_required(login_url='catalog:product_list')
def product_delete(request, product_id):
    product = cache.get('product_{}'.format(product_id))
    if product is None:
        product = get_object_or_404(Product, id=product_id)
    product.delete()
    return redirect('catalog:product_list')


def comment_create(request, product_id):
    product = cache.get('product_{}'.format(product_id))
    user = request.user
    if product is None:
        product = get_object_or_404(Product, id=product_id)
    if user.is_active:
        Comment.objects.create(product=product, user=user, text=request.POST.get('text'))
    return redirect('catalog:product_detail', product_id)


def comment_edit(request, comment_id, product_id):
    edit_comment = get_object_or_404(Comment, id=comment_id)
    if request.user == edit_comment.user:
        edit_comment.text = request.POST.get('text')
        edit_comment.updated_date = timezone.now()
        edit_comment.save()
    return redirect('catalog:product_detail', product_id)


def comment_delete(request, comment_id, product_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.user == request.user or request.user.is_staff:
        comment.delete()
    return redirect('catalog:product_detail', product_id)


def like(request, comment_id, product_id):
    if request.user.is_active:
        Like.objects.create(comment=get_object_or_404(Comment, id=comment_id), user=request.user)

    return redirect('catalog:product_detail', product_id)


def unlike(request, like_id, product_id):
    like_ = get_object_or_404(Like, id=like_id)
    if request.user == like_.user:
        like_.delete()
    return redirect('catalog:product_detail', product_id)


@staff_member_required(login_url='catalog:product_list')
def category_delete(request, id):
    get_object_or_404(Category, id=id).delete()
    return redirect('catalog:product_list')

catalog/templates/catalog/base_catalog.html
{% extends 'base.html' %}

{%block content%}

  {% include "navbar.html" %}

{%block catalog%}

{%endblock%}

{%endblock%}

catalog/templates/catalog/category_admin.html
{% extends 'base.html' %}
{%load static %}
{%block style%}
   <link rel="stylesheet" href="{% static 'css/catalog/category_admin.css' %}">
{%endblock%}
{%block content%}
    {% include "navbar.html" %}
<div class="container-fluid"><a href="{% url 'catalog:category_create'%}" class="btn btn-dark" style="background: #212529;">Category Create</a></div>
    <div class="category_admin">
            <div class="shadow">
                <ul class="list-group" style="margin-left: -5px">
                    {%for category in categories%}
                    <li>
                        <div class="list-group-item  list-group-item-action list-group-item-secondary">
                            <h5 style="text-align: center"><em><strong style="">{{category.title}}</strong></em></h5>
                             <div class="row justify-content-between">
                                <a href="{% url 'catalog:category_update' category.id%}" class="btn btn-dark" style="background: #212529">Update</a>
                                <a href="{% url 'catalog:category_delete' category.id%}" class="btn btn-dark" style="background: #212529">Delete</a>
                             </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
        </div>
    </div>
{%endblock%}

catalog/templates/catalog/category_create.html
{% extends 'base.html' %}
{%load static %}
{%block style%}
   <link rel="stylesheet" href="{% static 'css/catalog/category_create.css' %}">
{%endblock%}
{%block content%}
    {% include "navbar.html" %}

    <div class="container col-3" style="background: rgba(245, 35, 35, 0.5); border-radius: 10px; margin-bottom:-7%;margin-top: 3%; ">
        <strong>{{form.errors}}</strong>
    </div>
    {% if up_category %}
        <form enctype="multipart/form-data" action="{% url 'catalog:category_update' up_category.id%}" method="post">
    {%else%}
        <form enctype="multipart/form-data" action="{% url 'catalog:category_create'%}" method="post">
    {%endif%}
            {% csrf_token %}
        <div class="category_create">
            <h5 style="color:white; margin-left: 5px">{{form.title.label}}:</h5>
            {{form.title}}
            {% if up_category %}
                 <input type="submit" class="form-control" style="background: #ffc107; border-radius: 10px; margin-top: 10px"
                        value="Save"  aria-describedby="emailHelp">
             {%else%}
                 <input type="submit" class="form-control" style="background: #ffc107; border-radius: 10px; margin-top: 10px"
                         value="Update"  aria-describedby="emailHelp">
            {%endif%}
        </div>

    </form>

{%endblock%}

catalog/templates/catalog/product_detail.html
{%extends 'catalog/base_catalog.html'%}{%load static%} {%load catalog_tags %}
{%block style%}
    <link rel="stylesheet" href="{% static 'css/catalog/product_detail.css'%}">
    <link rel="stylesheet" href="{% static 'css/catalog/product_detail_media.css'%}">
{%endblock%}
{%block catalog%}


    <div class="container-fluid" >
        {%if user.is_staff%}
            <a href="{% url 'catalog:product_update' product.id %}" class="btn btn-dark" style="background: #212529">Update</a>
            <a href="{% url 'catalog:product_delete' product.id %}" class="btn btn-dark" style="background: #212529">Delete</a>
        {%endif%}
            <div class="row" style="margin-bottom: 5%;">

                 <div class="col-sm-12 col-md-7 col-lg-6 col-xl-5 mt-3">

                    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">

                            <div class="carousel-inner">

                                  <div class="carousel-item active">
                                    <img src="{{product.image.url}}"  class="image_product" alt="..." >
                                  </div>

                                    {% for i in product.images.all %}

                                        <div class="carousel-item">
                                             <img src="{{i.image.url}}"  class="image_product" alt="...">
                                        </div>

                                    {% endfor %}

                            </div>

                    </div>


                          <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>


                </div>


               <div class="col">
                    <div class="description">
                         <h1>{{ product.title }}</h1>
                         <p class="text-justify">{{ product.description}}</p>
                        <div class="row justify-content-between">
                            {%if product.quantity > 0%}
                                <form action="{% url 'cart:cart_add' product.id %}" method="POST">{% csrf_token %}
                                     <div class="row ">
                                        <div class="col"><button type="input" class="btn btn-dark" style="background: #212529">Add</button></div>
                                        <div class="col-auto" style="margin-left: -30px">{% csrf_token %} {{ cart_product_form }}</div>
                                    </div>
                                </form>
                            {%endif%}

                            <div class="col-auto">
                                <button type="button" value="Previous Page" class="btn btn-dark pull-right" style="background: #212529 margin-left: 15px" onClick="window.history.back();return false;">
                                    Back
                                </button>
                            </div>
                        </div>
                    </div>
               </div>
            </div>

        <div class="row">
            {%if user.is_authenticated%}
            <div class="col">
              <form action="{% url 'catalog:comment_create' product.id%}" method="POST"> {% csrf_token %}
                    <p class="label_form"><b>Введите ваш отзыв:</b></p>
                    <p><textarea class="comment_form" rows="10" cols="45" name="text"></textarea></p>
                    <p class="bottom_form"><input class="btn btn-dark" style="background: #212529" type="submit"  value="Send comment"></p>
              </form>
            {%endif%}
                  {%for comment in comments%}
                      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Edit comment</h5>
                              </div>
                                <form action="{% url 'catalog:comment_edit' comment.id product.id%}" method="POST"> {% csrf_token %}
                                  <div class="modal-body">
                                        <p><textarea class="form-control" rows="10" cols="45" name="text"></textarea></p>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                     <p style="margin-left: 740px"><input class="btn btn-dark" type="submit"  value="Edit"></p>
                                  </div>
                                </form>
                            </div>
                          </div>
                      </div>
                   {%if comment in user.comment.all%}
                        <div class="my_comment">
                   {%else%}
                        <div class="comment">
                   {%endif%}
                            <div class="row">
                            {%if comment not in user.comment.all%}
                                <div class="col-1">
                                    <img src="{{comment.user.main_image.url}}"  class="image_comment" alt="...">
                                </div>
                                <div class="col-2" style="margin-left: 75px">
                                    <strong>{{comment.user.user_name}}</strong>

                                </div>
                           {%endif%}
                           {%if comment in user.comment.all or user.is_staff%}
                                <div class="col-9">
                                    <div class="btn-group" id="btn_comment" role="group" aria-label="Basic example">
                                        <button type="button" class="btn btn-dark" id="Edit" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Edit</button>
                                        <a href="{% url 'catalog:comment_delete' comment.id product.id%}" class="btn btn-dark" id="Delete">Delete</a>
                                    </div>
                                </div>
                           {%endif%}
                                <div class="col-12">
                                    {{comment.text}}
                                </div>


                                        <div class="col-12" style="margin-top: 5px">
                                            {{comment.date_joined}}
                                        </div>
                                   {%if comment.edit_joined is None%}
                                        <div class="col-sm-12 col-md-7 col-lg-6 col-xl-10 mt-3" style="margin-top: 5px">
                                            Edit: {{comment.edit_joined}}
                                        </div>
                                   {%endif%}

                                        <div class="col-sm-12 col-md-7 col-lg-6 col-xl-1 mt-3">
                                            {%liked_comment user.like.all comment.like.all as like%}
                                            {%if like%}
                                                <a href="{% url 'catalog:unlike' like.id product.id%}" class="btn btn-dark">UnLike</a>
                                            {%else%}
                                                <a href="{% url 'catalog:like' comment.id product.id%}" class="btn btn-dark">Like</a>
                                            {%endif%}
                                            {{comment.like.count}}
                                        </div>
                            </div>

                   </div>
             {%endfor%}
            </div>
           </div>
        </div>
    </div>

{%endblock%}

catalog/templates/catalog/product_list.html
{%extends 'catalog/base_catalog.html'%}

{%block catalog%}

<div class="container-fluid" xmlns="http://www.w3.org/1999/html">
        {%if user.is_staff%}
            <a href="{% url 'catalog:product_create'%}" class="btn btn-dark" style="background: #212529">Product Create</a>
            <a href="{% url 'catalog:category_create'%}" class="btn btn-dark" style="background: #212529">Category Create</a>
        {%endif%}
        <h5>{{visit}}</h5>
        <div class="row">
                <div class="col-12 col-sm-12 col-md-4 col-lg-3 col-xl-2 mt-3">
                    <div class="shadow">
                        <ul class="list-group" style="margin-left: -5px">
                            {%if current_category%}
                                <li>
                                    <a href="/" class="list-group-item list-group-item-action list-group-item"><h6 style="text-align: center">All categories</h6></a>
                                </li>
                            {%else%}
                                <li >
                                    <a href="/" class="list-group-item list-group-item-action list-group-item-secondary"><h5 style="text-align: center"><em><strong>All categories</strong></em></h5></a>
                                </li>
                            {%endif%}

                            {%for category in categories%}
                                    <li>
                                        {%if category == current_category%}
                                        <a href="{{category.get_absolute_url}}" class="list-group-item list-group-item-secondary "><h5 style="text-align: center"><em><strong style="">{{category.title}}</strong></em></h5></a>
                                        {%else%}
                                        <a href="{{category.get_absolute_url}}" class="list-group-item list-group-item-action "><h6 style="text-align: center">{{category.title}}</h6></a>
                                        {%endif%}
                                    </li>
                            {% endfor %}
                            {%if user.is_staff%}
                                <li>
                                    <a href="{% url 'catalog:category_admin' %}" class="list-group-item list-group-item-action list-group-item" style="background: #212529;"><h5 style="color:white; text-align: center">Category administration</h5></a>
                                </li>
                            {%endif%}
                        </ul>
                    </div>
                </div>



             <style>
                   #list { width:100%; margin-left: auto; margin-right: -350px }
                   @media screen and (max-width: 990px) {
                     #list { width:100%; margin-left: 30px; }
                   }
             </style>
              <div class="col">
                  <div class="card-deck mt-3" style='width:100%; margin-left: auto;'>
                      {% for product in products %}
                      <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3">
                          <div class="card bg-light mb-3" style="max-width:rem 16;">
                              <img  height="100%" src="{{product.image.url}}"  style="width:100%;" class="card-img-top" alt="изображение продукта">
                              <div class="card-body" style='width:100%; height:100%;'>
                                  <h4 class="card-title">{{product.title}}</h4>

                                  <div class="row">
                                      <div class="col-sm-11 col-md-7"><p><strong>Price: {{product.price}}$</strong></p></div>
                                          {% if product.quantity > 0%}
                                              <div class="col"><p><strong>In stock: {{product.quantity}}</strong></p></div>
                                          {% else %}
                                              <div><strong><p class="text-danger">Нет в наличии</p></strong></div>
                                          {% endif %}
                                      </div>
                                      <a href="{{product.get_absolute_url}}" class="btn btn-dark" style="background: #212529">Detail</a>
                                      {%if user.is_staff%}
                                          <a href="{% url 'catalog:product_update' product.id %}" class="btn btn-dark" style="background: #212529">Update</a>
                                          <a href="{% url 'catalog:product_delete' product.id %}" class="btn btn-dark" style="background: #212529">Delete</a>
                                      {%endif%}
                                  </div>
                          </div>
                      </div>
                      {% endfor %}


                  </div>


              </div>

        </div>
        {% if is_paginated %}
                <nav aria-label="...">
                  <ul class="pagination justify-content-center">
                        <li class="page-item {%if not prev_url%}disabled{%endif%}">
                            <a class="page-link" href="{{prev_url}}" tabindex="-1" aria-disabled="true"><strong><p style="color:#212529">❮</p> </strong></a>
                        </li>



                        {%for n in products.paginator.page_range%}
                            {% if products.number == n%}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" href="?page={{n}}" style="background:#212529"><strong><p>{{n}}</p></strong><span class="sr-only">(current)</span></a>
                                </li>

                            {%elif n > products.number|add:-3 and n < products.number|add:3 %}

                                <li class="page-item">
                                    <a class="page-link" href="?page={{n}}"><strong><p style="color:#212529">{{n}}</p></strong></a>
                                </li>
                            {%endif%}
                        {%endfor%}

                        {%if next_url%}
                            <li class="page-item">
                                <a class="page-link" href="{{next_url}}" tabindex="-1" aria-disabled="true" style="background: #212529"><strong><p style="color:white">❯</p> </strong></a>
                            </li>
                        {%endif%}
                  </ul>
                </nav>
        {%endif%}
    </div>
{%endblock%}